src/Inodata/FloraBundle/Entity/Order.php
<?php

namespace Inodata\FloraBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo; // gedmo annotations

//use Doctrine\ORM\EntityRepository;

/**
 * Order.
 *
 * @Gedmo\Loggable
 * @ORM\Table(name="ino_order")
 * @ORM\Entity
 */
class Order
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="delivery_date", type="datetime", nullable=true)
     */
    private $deliveryDate;

    /**
     * @var string
     *
     * @ORM\Column(name="invoice_number", type="string", length=15, nullable=true)
     */
    private $invoiceNumber;

    /**
     * @var int
     *
     * @ORM\Column(name="purchase_order", type="string", length=32, nullable=true)
     */
    private $purchaseOrder;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="invoice_date", type="datetime", nullable=true)
     */
    private $invoiceDate;

    /**
     * @var bool
     *
     * @ORM\Column(name="is_external", type="boolean", nullable=true)
     */
    private $isExternal;

    /**
     * @var float
     *
     * @ORM\Column(name="shipping", type="float", nullable=true)
     */
    private $shipping;

    /**
     * @var float
     *
     * @ORM\Column(name="discount", type="float", nullable=true)
     */
    private $discount;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="\Application\Sonata\UserBundle\Entity\User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="creator_id", referencedColumnName="id")
     * })
     */
    private $creator;

    /**
     * @var string
     * @ORM\Column(name="reporter", type="string", length=32, nullable=true)
     */
    private $reporter;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     * @Gedmo\Timestampable(on="update")
     */
    private $updatedAt;

    /**
     * @var string
     *
     * @ORM\Column(name="from_person", type="string", length=255, nullable=true)
     */
    private $from;

    /**
     * @var string
     *
     * @ORM\Column(name="to_person", type="string", length=255, nullable=true)
     */
    private $to;

    /**
     * @var string
     *
     * @ORM\Column(name="message", type="text", nullable=true)
     */
    private $message;

    /**
     * @var \Address
     *
     * @ORM\ManyToOne(targetEntity="Address", cascade={"persist"})
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="shipping_address_id", referencedColumnName="id", onDelete="CASCADE")
     * })
     */
    private $shippingAddress;

    /**
     * @var \Customer
     *
     * @ORM\ManyToOne(targetEntity="Customer")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="customer_id", referencedColumnName="id")
     * })
     */
    private $customer;

    /**
     * @var \Employee
     *
     * @ORM\ManyToOne(targetEntity="Employee")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="messenger_id", referencedColumnName="id")
     * })
     */
    private $messenger;

    /**
     * @var \Employee
     *
     * @ORM\ManyToOne(targetEntity="Employee")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="collector_id", referencedColumnName="id")
     * })
     */
    private $collector;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="collection_date", type="datetime", nullable=true)
     */
    private $collectionDate;

    /**
     * @var \PaymentContact
     *
     * @ORM\ManyToOne(targetEntity="PaymentContact")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="payment_contact_id", referencedColumnName="id")
     * })
     */
    private $paymentContact;

    /**
     * @var string
     * @ORM\Column(type="string", columnDefinition="ENUM('open','intransit','delivered','partiallypayment','closed')")
     */
    private $status;

    /**
     * @var string
     *
     * @ORM\Column(name="payment_condition", type="string", length=255, nullable=true)
     */
    private $paymentCondition;

    /**
     * @var string
     *
     * @ORM\Column(name="order_notes", type="string", length=255, nullable=true)
     */
    private $order_notes;

    /**
     * @var string
     *
     * @ORM\Column(name="invoice_comment", type="string", length=255, nullable=true)
     */
    private $invoiceComment;

    /**
     * @var bool
     *
     * @ORM\Column(name="has_invoice", type="boolean", nullable=true)
     */
    private $hasInvoice;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->hasInvoice = false;
        $this->deliveryDate = new \DateTime('NOW');
        $this->invoiceDate = new \DateTime('NOW');
        $this->status = 'open';
    }

    /**
     * @return string
     */
    public function __toString()
    {
        $orderId = $this->id;
        if (empty($this->id)) {
            $orderId = '';
        }

        $product = $this->getFirstProduct();

        if ($product != '') {
            return ''.$orderId.' - '.$product->getDescription();
        }

        return ''.$orderId;
    }

    public function getFirstProduct()
    {
        global $kernel;

        if ('AppCache' == get_class($kernel)) {
            $kernel = $kernel->getKernel();
        }

        $em = $kernel->getContainer()->get('doctrine.orm.entity_manager');
        $repository = $em->getRepository('InodataFloraBundle:OrderProduct');
        $orderProduct = $repository->findOneByOrder($this->getId());

        if ($orderProduct) {
            return $orderProduct->getProduct();
        }

        return '';
    }

    public function getFirstProductPrice()
    {
        $firstProduct = $this->getFirstProduct();

        if (!$firstProduct) {
            return 0;
        }

        return $firstProduct->getPrice();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Function only for resolve a problem with edit.
     *
     * @param int $id
     *
     * @return Order
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Set deliveryDate.
     *
     * @param \DateTime $deliveryDate
     *
     * @return Order
     */
    public function setDeliveryDate($deliveryDate)
    {
        $this->deliveryDate = $deliveryDate;

        return $this;
    }

    /**
     * Get deliveryDate.
     *
     * @return \DateTime
     */
    public function getDeliveryDate()
    {
        return $this->deliveryDate;
    }

    /**
     * Set invoiceNumber.
     *
     * @param string $invoiceNumber
     *
     * @return Order
     */
    public function setInvoiceNumber($invoiceNumber)
    {
        $this->invoiceNumber = $invoiceNumber;

        return $this;
    }

    /**
     * Get invoiceNumber.
     *
     * @return string
     */
    public function getInvoiceNumber()
    {
        return $this->invoiceNumber;
    }

    /**
     * Set isExternal.
     *
     * @param bool $isExternal
     *
     * @return Order
     */
    public function setIsExternal($isExternal)
    {
        $this->isExternal = $isExternal;

        return $this;
    }

    /**
     * Get isExternal.
     *
     * @return bool
     */
    public function getIsExternal()
    {
        return $this->isExternal;
    }

    /**
     * Set shipping.
     *
     * @param float $shipping
     *
     * @return Order
     */
    public function setShipping($shipping)
    {
        $this->shipping = $shipping;

        return $this;
    }

    /**
     * Get shipping.
     *
     * @return float
     */
    public function getShipping()
    {
        return $this->shipping;
    }

    /**
     * Set discount.
     *
     * @param float $discount
     *
     * @return Order
     */
    public function setDiscount($discount)
    {
        $this->discount = $discount;

        return $this;
    }

    /**
     * Get discount.
     *
     * @return float
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * Set creator.
     *
     * @param \Application\Sonata\UserBundle\Entity\User $creator
     *
     * @return Order
     */
    public function setCreator(\Application\Sonata\UserBundle\Entity\User $creator)
    {
        $this->creator = $creator;

        return $this;
    }

    /**
     * Get creator.
     *
     * @return \Application\Sonata\UserBundle\Entity\User
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Set createdAt.
     *
     * @param \DateTime $createdAt
     *
     * @return Order
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt.
     *
     * @param \DateTime $updatedAt
     *
     * @return Order
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set from.
     *
     * @param string $from
     *
     * @return Order
     */
    public function setFrom($from)
    {
        $this->from = $from;

        return $this;
    }

    /**
     * Get from.
     *
     * @return string
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Set to.
     *
     * @param string $to
     *
     * @return Order
     */

src/Inodata/FloraBundle/Entity/Product.php
<?php

namespace Inodata\FloraBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Product.
 *
 * @ORM\Table(name="ino_product")
 * @ORM\Entity
 */
class Product
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="code", type="string", length=255, unique=true, nullable=false)
     */
    private $code;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @var float
     *
     * @ORM\Column(name="price", type="decimal", nullable=false)
     */
    private $price;

    /**
     * @var int
     *
     * @ORM\Column(name="stock", type="integer", nullable=true)
     */
    private $stock;

    /**
     * @ORM\ManyToMany(targetEntity="Category", cascade={"persist"})
     * @ORM\JoinTable(name="ino_products_categories",
     *      joinColumns={@ORM\JoinColumn(name="product_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="category_id", referencedColumnName="id")}
     * )
     */
    private $categories;

    /**
     * @return string
     */
    public function __toString()
    {
        if (!empty($this->description)) {
            if (substr($this->code, 0, 1) == 'X') {
                return $this->description;
            } else {
                return $this->code.' - '.$this->description;
            }
        } else {
            return ' ';
        }
    }

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->categories = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set description.
     *
     * @param string $description
     *
     * @return Product
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set price.
     *
     * @param float $price
     *
     * @return Product
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price.
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set stock.
     *
     * @param int $stock
     *
     * @return Product
     */
    public function setStock($stock)
    {
        $this->stock = $stock;

        return $this;
    }

    /**
     * Get stock.
     *
     * @return int
     */
    public function getStock()
    {
        return $this->stock;
    }

    /**
     * Set code.
     *
     * @param int $code
     *
     * @return Product
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get code.
     *
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Add categories.
     *
     * @param \Inodata\FloraBundle\Entity\Category $categories
     *
     * @return Product
     */
    //TODO: Eliminar este método (refactor)
    public function addCategorie(\Inodata\FloraBundle\Entity\Category $categories)
    {
        $this->categories[] = $categories;

        return $this;
    }

    /**
     * @return string
     */
    public function getPriceInLetters()
    {
        $letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'];
        $numbers = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'];

        return str_replace($numbers, $letters, $this->price);
    }

    /**
     * Add categories.
     *
     * @param \Inodata\FloraBundle\Entity\Category $categories
     *
     * @return Product
     */
    public function addCategory(\Inodata\FloraBundle\Entity\Category $categories)
    {
        $this->categories[] = $categories;

        return $this;
    }

    /**
     * Remove categories.
     *
     * @param \Inodata\FloraBundle\Entity\Category $categories
     */
    public function removeCategory(\Inodata\FloraBundle\Entity\Category $categories)
    {
        $this->categories->removeElement($categories);
    }

    /**
     * Get categories.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * Remove categories.
     *
     * @param \Inodata\FloraBundle\Entity\Category $categories
     */
    //TODO: Eliminar este método (refactor)
    public function removeCategorie(\Inodata\FloraBundle\Entity\Category $categories)
    {
        $this->categories->removeElement($categories);
    }
}

src/Inodata/FloraBundle/Resources/views/Order/_dinamic_select_item.html.twig
{% if contact is defined %}
	<option value="{{ contact.id }}" selected="selected">{{ contact.name }}</optio>
{% endif %}

{% if contacts is defined %}
	<option value=""></option>
	{% for contact in contacts %}
		<option value="{{ contact.id }}">{{ contact.name }}</option>
	{% endfor %}
{% endif %}

{% if messages is defined %}
	<option value=""></option>
	{% for message in messages %}
		<option value="{{ message.id }}">{{ message.message }}</option>
	{% endfor %}
{% endif %}

src/Inodata/FloraBundle/Resources/views/Order/_dynamic_select_item.html.twig
{% if contact is defined %}
	<option value="{{ contact.id }}" selected="selected">{{ contact.name }}</optio>
{% endif %}

{% if contacts is defined %}
	<option value=""></option>
	{% for contact in contacts %}
		<option value="{{ contact.id }}">{{ contact.name }}</option>
	{% endfor %}
{% endif %}

{% if messages is defined %}
	<option value=""></option>
	{% for message in messages %}
		<option value="{{ message.id }}" content="{{ message.message }}">{{ message }}</option>
	{% endfor %}
{% endif %}

src/Inodata/FloraBundle/Resources/views/Order/_invoice_product_item.html.twig
<tr product_id={{ orderProduct.id }}>
	<td class="sonata-ba-list-field sonata-ba-list-field-text" >
		{{total}}
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text">
		<a href="#" class="product-x-editable" data-name="unit" data-type="text" data-pk="{{ orderProduct.id}}">
			{{ orderProduct.unit}}
		</a>
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text">
		<a href="#" class="product-x-editable" data-name="date" data-type="date" data-pk="{{ orderProduct.id}}"
			data-viewformat="dd/mm/yyyy">
			{% if orderProduct.invoiceDate !=""%}
				{{ orderProduct.invoiceDate|date("d/m/Y")}}
			{% endif %}
		</a>
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text details" >
		{{ orderProduct.product.description }}
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text price" >
		{{ orderProduct.product.price }}
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text import" >
		{{ orderProduct.product.price * total}}
	</td>
</tr>

src/Inodata/FloraBundle/Resources/views/Order/_note_product_item.html.twig
<tr id="" product_id={{ product.id }}>
	<td class="sonata-ba-list-field sonata-ba-list-field-text" >
		{{total}}
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text details" >
		{{ product }} ({{ product.priceInLetters }})
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text price" >
		{{ product.price }}
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text import" >
		{{ product.price * total}}
	</td>
</tr>

src/Inodata/FloraBundle/Resources/views/Order/_product_item.html.twig
<tr id="product-{{ product.id }}" class="product" product_id={{ product.id }}>
	<td class="sonata-ba-list-field sonata-ba-list-field-text" >
		<input type="text" class="product-total" value="{{total}}" style="width: 25px; text-align: center;"/>
		<input type="hidden" name="product[{{ product.id }}]" id="data_product_{{ product.id }}" value="{{ total }}"/>
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text details" >
		{{ product }} ({{ product.priceInLetters }})
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text price" >
		{{ product.price }}
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text import" >
		{{ product.price * total}}
	</td>
	<td class="sonata-ba-list-field sonata-ba-list-field-text" >
		<a href="javascript:void()" class="btn delete_link" title="Borrar">
			<i class="icon-remove"></i>Borrar
		</a>
	</td>
</tr>

src/Inodata/FloraBundle/Resources/views/Order/_select_order_option.html.twig
<input type="hidden" name="product[{{ product.id }}]" id="data_product_{{ product.id }}" value="{{ total }}"/>

src/Inodata/FloraBundle/Resources/views/Order/card.html.twig
<div class="card_page">
	<div class= "card_header">&nbsp;</div>
	<div class= "card_data">
		<div class="card_to"></div>
		<div class="card_message">
			<table class="message_container">
				<tbody>
					<tr><td style="vertical-align:middle"></td></tr>
				</tbody>
			</table>
		</div>
		<div class="card_from"></div>
	</div>	
</div>
<a href="javascript:void();" class="btn btn-print-card" title="{{ 'button.print_card'|trans({}, 'InodataFloraBundle') }}">
    <i class="icon-print"></i>{{ 'button.print_card'|trans({}, 'InodataFloraBundle') }}
</a>

src/Inodata/FloraBundle/Resources/views/Order/card2.html.twig
<div class="card_page">
	<div class= "card_header"><img class="img_header" src="{{ asset('bundles/inodataflora/img/note_header.png') }}"></div>
	<div class= "card_data">
		<div class="label_to"><strong>Para: </strong></div>
		<div class="card_to"></div>
		<div class="card_message">
			<table class="message_container">
				<tbody>
					<tr><td style="vertical-align:middle"></td></tr>
				</tbody>
			</table>
		</div>
		<div class="label_from"><strong>De: </strong></div>
		<div class="card_from"></div>
	</div>	
</div>
<a href="javascript:void();" class="btn btn-print-card" title="{{ 'button.print_card'|trans({}, 'InodataFloraBundle') }}">
    <i class="icon-print"></i>{{ 'button.print_card'|trans({}, 'InodataFloraBundle') }}
</a>

src/Inodata/FloraBundle/Resources/views/Order/edit.html.twig
{% extends 'InodataFloraBundle::base_edit.html.twig' %}

{% block stylesheets %}
	{{ parent() }}
	{% stylesheets 
      '@InodataFloraBundle/Resources/public/css/order_screen.css'%}
		<link rel="stylesheet" href="{{ asset_url }}" />
	{% endstylesheets %}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
  <script type="text/javascript">
    //Imports printers from parameters.yml via twig globals
    //Medium Letter Paper Size
    var note_printer = "{{ note_printer }}";
    var card_printer = "{{ card_printer }}";
    //Letter Paper Size
    var invoice_printer = "{{ invoice_printer }}";
  </script>	
	{% javascripts 
  	   "@InodataFloraBundle/Resources/public/js/order_admin.js"
       "@InodataFloraBundle/Resources/public/js/print.js"
       "@InodataFloraBundle/Resources/public/js/customer_admin.js"
       %}
    <script type="text/javascript" src="{{ asset_url }}" ></script>
	{% endjavascripts %}
{% endblock %}

{% block form %}
    {{ parent() }}
    {% if admin.id(object) %}
        {# copia #}
        {% embed 'InodataFloraBundle:Order:payment_note_2.html.twig' with {'note': 1} %} {% endembed %}
        {# archivo #}
        {#  {% embed 'InodataFloraBundle:Order:payment_note_2.html.twig' with {'note': 2} %} {% endembed %} #}
        {# original #}
        {% embed 'InodataFloraBundle:Order:payment_note_2.html.twig' with {'note': 3} %} {% endembed %}
    {% endif %}
{% endblock %}

{% block sonata_fieldsets %}
    <div class="tab-content order-capture">
        {% for name, form_group in admin.formgroups %}            
            {% if name == "tab.invoice" %}
                <div class="tab-pane {% if loop.first %} active{% endif %}" id="{{ admin.uniqid }}_{{ loop.index }}">
                    {{ block('sonata_fieldset') }}
                    {% if admin.id(object) %}
                    	{#{% embed 'InodataFloraBundle:Order:payment_note.html.twig' %}{% endembed %}#}
                    	{% if object.hasInvoice==1 %}
                    		{% embed 'InodataFloraBundle:Order:invoice.html.twig' %}{% endembed %}
                      {% else %}
                        {# TODO: Meter un botón para activar los datos de factura sin necesidad del click en checkbox y actualizar el pedido.
                          <a href="#" class="btn btn-success"><i class="icon-list-alt"></i>{{ 'button.activate_invoice'|trans({}, 'InodataFloraBundle')}}</a>
                        #}
                    	{% endif %}
                    {% else %}
                    	<div class="no-invoice-msg">Para facturar, primero debe crear la orden.</div>
                    {% endif %}
                    {% embed 'InodataFloraBundle:Order:card2.html.twig' %}{% endembed %}
                </div>
            {% else %}
                <div class="tab-pane {% if loop.first %} active{% endif %}" id="{{ admin.uniqid }}_{{ loop.index }}">
                    {{ block('sonata_fieldset') }}
                    <div class="create-product-form">
                    	<div class="product-code"><label>Clave</label><input type="text" /></div>
                    	<div class="product-description"><label>Descripción</label></label><input type="text"/></div>
                    	<div class="product-price"><label>Precio</label><input type="text"/></div>
                    	<div class="product-action"><label>&nbsp;</label>
                    		<a href="javascript:void()" class="btn create-and-add-product">Crear y Agregar</a>
                    	</div>
                    </div>
                    {% embed 'InodataFloraBundle:Order:products_table.html.twig' %}{% endembed %}
                    <div class="order-data frame"><span>Datos del pedido</span></div>
                    <div class="delivery-address frame"><span>Dirección de entrega</span></div>
                    <div class="customer-data frame"><span>Datos del cliente</span></div>
                    <div class="message-data frame"><span>Mensaje para la tarjeta</span></div>
                    <div class="products_to_order frame"><span>Productos del pedido</span></div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}
{% block formactions %}
	{{ parent() }}
	<input type="submit" name="save_and_print_note" class="btn btn-print" value="{{ 'button.print_note'|trans({}, 'InodataFloraBundle')}}"/>
  {% if object.hasInvoice == 1 %}
    <input type="submit" name="save_and_print_invoice" class="btn btn-print" value="{{ 'button.print_invoice'|trans({}, 'InodataFloraBundle')}}"/>
  {% endif %}	
	{% if admin.id(object) %}
		<input type="hidden" class="post_save_action" value="{{ app.session.get('post_save_action') }}" />
	{% endif %}
        
    {% if admin.id(object) %}
        <input type="submit" class="btn btn-primary save_as-new" value ="Guardar como nuevo" url="{{path("admin_inodata_flora_order_create")}}">
    {% endif %}
{% endblock formactions %}

src/Inodata/FloraBundle/Resources/views/Order/list.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list.html.twig' %}
{% block javascripts %}
	{{ parent() }}	
	<script type="text/javascript">
		$(document).ready(function() {
			$('.js-datepicker').datepicker({ dateFormat: 'yy-mm-dd' });			
		});
	</script>
{% endblock %}