src/Inodata/FloraBundle/Form/Type/AddressType.php
<?php

namespace Inodata\FloraBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class AddressType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('street', null, ['label' => 'label.street'])
            ->add('noExt', null, ['label' => 'label.exterior'])
            ->add('noInt', null, ['label' => 'label.interior'])
            ->add('reference', null, ['label' => 'label.reference'])
            ->add('neighborhood', 'ajax_autocomplete', ['label' => 'label.neighborhood',
                'attr'                                          => [
                    'placeholder' => 'label.select_neighborhood',
                    'class'       => 'ajax-autocomplete shipping_neighborhood',
                    'entity'      => 'InodataFloraBundle:GuiaRoji',
                    'column'      => 'neighborhood', ],
            ])
            ->add('city', null, ['label' => 'label.city', 'attr' => ['class' => 'shipping_city']])
            ->add(
                'state',
                'inodata_mx_states_type',
                ['label'   => 'label.state',
                    'attr' => ['class'=>'mx_state'],
                ]
            )
            ->add('postalCode', null, ['label' => 'label.postal_code', 'attr' => ['class' => 'shipping_postal_code']])
            ->add('phone', null, ['label' => 'label.delivery_phone']);
    }

    public function getName()
    {
        return 'inodata_address_form';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'data_class'         => 'Inodata\FloraBundle\Entity\Address',
            'translation_domain' => 'InodataFloraBundle',
            //TODO: Implementar el tipo de dirección como etiqueta.
            'label' => false,
        ]);
    }
}

src/Inodata/FloraBundle/Form/Type/AddressTypeType.php
<?php

namespace Inodata\FloraBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class AddressTypeType extends AbstractType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'choices' => [
                'Delivery' => 'Delivery',
                'Fiscal'   => 'Fiscal',
                'Shipping' => 'Shipping',
                'Billing'  => 'Billing',
            ],
            'translation_domain' => 'InodataFloraBundle',
        ]);
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'inodata_address_type_type';
    }
}

src/Inodata/FloraBundle/Form/Type/AjaxAutocompleteType.php
<?php

namespace Inodata\FloraBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Description of AjaxAutcompleteType.
 *
 * @author heri
 */
class AjaxAutocompleteType extends AbstractType
{
    //@Overriden
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'attr' => ['class' => 'ajax-autocomplete'],
        ]);
    }

    //@Overriden
    public function getParent()
    {
        return 'text';
    }

    public function getName()
    {
        return 'ajax_autocomplete';
    }
}

src/Inodata/FloraBundle/Form/Type/AjaxEntityType.php
<?php

namespace Inodata\FloraBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Description of AjaxEntityType.
 *
 * @author heri
 */
class AjaxEntityType extends AbstractType
{
    //@Overriden
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'attr' => [
                'class' => 'ajax-entity',
                'query' => null,
            ],
        ]);
    }

    //@Overriden
    public function getParent()
    {
        return 'entity';
    }

    public function getName()
    {
        return 'ajax_entity';
    }
}

src/Inodata/FloraBundle/Form/Type/CollectionType.php
<?php

namespace Inodata\FloraBundle\Form\Type;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CollectionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //TODO: Probar con sonata_type_model, al hacer el request de ajax no respeta el query builder
        $builder
            ->add('id', 'ajax_entity', [
                'required'      => false,
                'class'         => 'InodataFloraBundle:Order',
                'empty_value'   => '',
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->where('u.status = \'delivered\'')
                        ->andWhere('u.collector IS NULL');
                },
                'attr'          => [
                    'class'       => 'inodata_id_list span5',
                    'entity'      => 'InodataFloraBundle:Order', 'columns' => 'id',
                    'placeholder' => 'Selecciona una órden',
                    'allowClear'  => 'true',
                ],
            ]);
    }

    public function getName()
    {
        return 'inodata_collection_type_form';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'         => 'Inodata\FloraBundle\Entity\Order',
            'translation_domain' => 'InodataFloraBundle',
        ]);
    }
}

src/Inodata/FloraBundle/Form/Type/CustomerType.php
<?php

namespace Inodata\FloraBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class CustomerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'member',
            'genemu_jqueryautocompleter_entity',
            ['class' => 'Genemu\Bundle\EntityBundle\Entity\Member']
        );
    }

    public function getParent()
    {
        return 'text';
    }

    public function getName()
    {
        return 'inodata_customer_type';
    }
}

src/Inodata/FloraBundle/Form/Type/DistributionType.php
<?php

namespace Inodata\FloraBundle\Form\Type;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DistributionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //TODO: Probar con sonata_type_model, al hacer el request de ajax no respeta el query builder
        $builder
            ->add('id', 'ajax_entity', [
                'required'      => false,
                'class'         => 'InodataFloraBundle:Order',
                'empty_value'   => '',
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->where('u.status = \'open\'')
                        ->andWhere('u.messenger IS NULL');
                },
                'attr'          => [
                    'class'       => 'inodata_id_list span5',
                    'entity'      => 'InodataFloraBundle:Order', 'columns' => 'id',
                    'placeholder' => 'Selecciona una órden',
                    'allowClear'  => 'true',
                ],
            ])
            ->add('messenger', 'genemu_jqueryselect2_entity', [
                'required'      => false,
                'empty_value'   => '',
                'class'         => 'Inodata\FloraBundle\Entity\Employee',
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->where('u.jobPosition = \'Messenger\'');
                },
                'attr'          => [
                    'class'       => 'inodata_messenger_list span5 ajax-entity',
                    'placeholder' => 'Selecciona un repartidor',
                    'enabled'     => 'enabled',
                ],
            ]);
    }

    public function getName()
    {
        return 'inodata_distribution_type_form';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'         => 'Inodata\FloraBundle\Entity\Order',
            'translation_domain' => 'InodataFloraBundle',
        ]);
    }
}

src/Inodata/FloraBundle/Form/Type/EmpPositionsType.php
<?php

namespace Inodata\FloraBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class EmpPositionsType extends AbstractType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'choices' => [
                'Messenger' => 'Messenger',
                'Collector' => 'Collector',
            ],
            'translation_domain' => 'InodataFloraBundle',
        ]);
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'inodata_emp_positions_type';
    }
}

src/Inodata/FloraBundle/Form/Type/MxStatesType.php
<?php

namespace Inodata\FloraBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class MxStatesType extends AbstractType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'choices' => [
                'DF'  => 'Distrito Federal',
                'AGS' => 'Aguascalientes',
                'BCN' => 'Baja California',
                'BCS' => 'Baja California Sur',
                'CAM' => 'Campeche',
                'CHP' => 'Chiapas',
                'CHI' => 'Chihuahua',
                'COA' => 'Coahuila de Zaragoza',
                'COL' => 'Colima',
                'DUR' => 'Durango',
                'GTO' => 'Guanajuato',
                'GRO' => 'Guerrero',
                'HGO' => 'Hidalgo',
                'JAL' => 'Jalisco',
                'MEX' => 'Estado de México',
                'MIC' => 'Michoacán de Ocampo',
                'MOR' => 'Morelos',
                'NAY' => 'Nayarit',
                'NL'  => 'Nuevo León',
                'OAX' => 'Oaxaca',
                'PUE' => 'Puebla',
                'QRO' => 'Querétaro',
                'ROO' => 'Quintana Roo',
                'SLP' => 'San Luis Potosí',
                'SIN' => 'Sinaloa',
                'SON' => 'Sonora',
                'TAB' => 'Tabasco',
                'TAM' => 'Tamaulipas',
                'TLX' => 'Tlaxcala',
                'VER' => 'Veracruz de Ignacio de la Llave',
                'YUC' => 'Yucatán',
                'ZAC' => 'Zacatecas',
            ],
            'preferred_choices' => ['NL'],
        ]);
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'inodata_mx_states_type';
    }
}

src/Inodata/FloraBundle/Form/Type/PaymentContactType.php
<?php

namespace Inodata\FloraBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PaymentContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'hidden')
            ->add(
                'department',
                null,
                [
                    'label' => 'label.department', ]
            )
            ->add(
                'employeeNumber',
                null,
                [
                    'label' => 'label.employee_number', ]
            )
            ->add(
                'phone',
                null,
                [
                    'label' => 'label.phone', ]
            )
            ->add(
                'extension',
                null,
                [
                    'label' => 'label.extension', ]
            )
            ->add(
                'email',
                null,
                [
                    'label' => 'label.email',
                ]
            );
    }

    public function getName()
    {
        return 'inodata_payment_contact_form';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'data_class'         => 'Inodata\FloraBundle\Entity\PaymentContact',
            'translation_domain' => 'InodataFloraBundle',
        ]);
    }
}

src/Inodata/FloraBundle/Resources/views/Form/fields.html.twig
{% block inodata_mx_states_widget %}
    {% spaceless %}
        {% if expanded %}
            <ul {{ block('widget_container_attributes') }}>
            {% for child in form %}
                <li>
                    {{ form_widget(child) }}
                    {{ form_label(child) }}
                </li>
            {% endfor %}
            </ul>
        {% else %}
            {# just let the choice widget render the select tag #}
            {{ block('choice_widget') }}
        {% endif %}
    {% endspaceless %}
{% endblock %}

{% block ajax_entity_widget %}
    {% spaceless %}
        <input type="text" class="ajax-entity {% if form.vars.attr['class'] is defined %}{{form.vars.attr['class']}}{%endif%}"
            {% for index, attr in form.vars.attr %} {%if index != "class" %}{{index}} = "{{attr}}"{%endif%}{%endfor%}
            id ="{{form.vars.id}}" name="{{form.vars.full_name}}" value="{{form.vars.value}}" text="{{form.vars.data}}"></input>
    {% endspaceless %}
{% endblock %}

{% block admin_product_sonata_type_collection_widget %}
    <div id="table-order-products">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>{%trans from "InodataImperaBundle"%}label.stock{%endtrans%}</th>
                <th>{%trans from "InodataImperaBundle"%}label.created_by{%endtrans%}</th>
                <th>{%trans from "InodataImperaBundle"%}label.created_at{%endtrans%}</th>
                <th>{{"label.actions"|trans([], "InodataImperaBundle")}}</th>
            </tr>
            </thead>
            <tbody>
                {% for stock in  form %}
                    <tr>
                        <td>{{ stock['stock'].vars.value }}</td>
                        <td>{{ stock['created_by']}}</td>
                        <td></td>
                        <td></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

src/Inodata/FloraBundle/Resources/views/Form/fields_impera.html.twig
{% use 'SonataAdminBundle:Form:form_admin_fields.html.twig' %}

{% block admin_order_sonata_type_collection_widget %}
    <div id="table-order-products">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>{%trans from "InodataImperaBundle"%}label.quantity{%endtrans%}</th>
                    <th>{%trans from "InodataImperaBundle"%}label.code{%endtrans%}</th>
                    <th>{%trans from "InodataImperaBundle"%}label.product_description{%endtrans%}</th>
                    <th>{%trans from "InodataImperaBundle"%}label.product_price{%endtrans%}</th>
                    <th>{%trans from "InodataImperaBundle"%}label.discount{%endtrans%}</th>
                    <th>{%trans from "InodataImperaBundle"%}label.subtotal{%endtrans%}</th>
                    <th>{{"label.actions"|trans([], "InodataImperaBundle")}}</th>
                </tr>
            </thead>
            <tbody>
                <tr id="product-entry">
                    <td><input type="text" value="1" id="entry-quantity"/></td>
                    <td><input type="text" id="entry-code"/></td>
                    <td>
                        <input type="text" id="entry-product" placeholder="{{"label.write_and_select_product"|trans([], "InodataImperaBundle")}}"/>
                    </td>
                    <td>
                        <a href="#" class="product-editable" id="entry-price" data-pk="" data-url="{{path("inodata_impera_product_ajax_editinplace")}}" data-type ="text" data-name="salePrice"
                            data-title ="{{"label.write_new_price"|trans({},"InodataImperaBundle")}}">0</a>
                    </td>
                    <td><input type="text" value="{% if form.parent['customer'].vars.data is not null %}{{ form.parent['customer'].vars.data.discount}}{% else %}0{% endif %}"
                               id="entry-discount"/> %</td>
                    <td id="entry-subtotal">0</td>
                    <td>
                        <a href="{{path("inodata_impera_orderproduct_ajax_add", {"uniqid": form.parent.vars.id})}}" class="btn" id="entry-add"
                           title="{{"label.add"|trans({}, "InodataImperaBundle")}}">
                            <i class="icon-plus"></i></a>
                    </td>
                </tr>

                {% for product in form%}
                    {% include 'InodataImperaBundle:OrderProduct:order_product.html.twig'%}
                {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock%}

{% block admin_order_sonata_type_model_hidden_widget %}
    <div class="control-group">
        <label class="control-label required">{{form.vars.label|trans({},'InodataImperaBundle')}}</label>
        <div class="controls sonata-ba-field sonata-ba-field-standard-natural order-sales-agent" id="">{{form.vars.data}}</div>
        <input type="hidden" id="{{form.vars.id}}" name="{{form.vars.full_name}}" value="{{form.vars.value}}" maxlength="45" class="span5 order-sales-agent">
    </div>
    {{block("sonata_type_model_hidden_widget")}}
{% endblock %}

{% block admin_purchase_order_hidden_widget %}
    {% include 'InodataImperaBundle:PoPurchaseOrder:_requisition_products.html.twig' %}
{% endblock %}

{% block admin_purchase_reception_hidden_widget %}
    {% if form.vars.name == 'products'%}
    {% else %}
        {{ block('hidden_widget') }}
    {% endif %}
{% endblock %}

{% block admin_purchase_reception_sonata_type_model_widget %}
    {% if form.vars.name == 'requisitionProduct'%}
        <input type="hidden" value="{{form.vars.value}}" id="{{form.vars.id}}" name="{{form.vars.full_name}}">
    {% else %}
        {{ block('hidden_widget') }}
    {% endif %}
{% endblock %}

{% block admin_purchase_payment_hidden_widget %}
    {% if form.vars.name == 'products' %}
        {% include 'InodataImperaBundle:PoPayment:_po_invoice_products.html.twig' %}
    {% else %}
        {{block('hidden_widget')}}
    {% endif %}
{% endblock %}

{% block admin_order_hidden_widget %}
    {% if form.vars.name == 'totals'%}
        <div id="order-totals">
            <table class="table table-bordered pay-table">
                <thead>
                    <tr><th colspan="2">{{"label.totals"|trans({}, "InodataImperaBundle")}}</th></tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{"label.discount"|trans({}, "InodataImperaBundle")}} (-):</td>
                        <td>$
                            <span class="order-discount" >{{ form.vars.data['discount']|number_format(2, '.', ',')}}</span>
                        </td>
                    </tr>
                    <tr><td>{{"label.subtotal"|trans({}, "InodataImperaBundle")}}:</td>
                        <td>$
                            <span class="order-subtotal">{{ form.vars.data['subtotal']|number_format(2, '.', ',')}}</span>
                        </td>
                    </tr>
                    <tr class="iva-container">
                        <td>IVA(16%):</td>
                        <td>$
                            <span class="order-iva">{{ form.vars.data['iva']|number_format(2, '.', ',')}}</span>
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th>{{"label.total"|trans({}, "InodataImperaBundle")}}:</th>
                        <th>$
                            <span class="order-total">{{ form.vars.data['total']|number_format(2, '.', ',')}}</span>
                        </th>
                    </tr>
                </tfoot>
            </table>
        </div>
    {% endif%}

    {% if form.vars.name == 'customer_details' %}
        <div class="customer-details-container">
            {% if form.parent['customer'].vars.value > 0 %}
                <a href="{{ path('inodata_impera_customer_ajax_get_details', {customerId: form.parent['customer'].vars.value})}}" class="btn btn-small" id="ino_customer_details">
                    {{'label.customer_details'|trans({}, 'InodataImperaBundle')}}</a>
            {% else %}
                <a href="{{ path('inodata_impera_customer_ajax_get_details', {customerId: 0 })}}" class="btn btn-small" id="ino_customer_details">
                    {{'label.customer_details'|trans({}, 'InodataImperaBundle')}}</a>
            {% endif %}
        </div>
    {% endif %}

    {% if form.vars.name == 'emails' %}
        <div class="control-group {% if form.parent['is_canceled'].vars.data == true%}invoice_canceled{% endif %}" id="sonata-ba-field-container-{{form.vars.id}}">
            {% if form.parent['id'].vars.value != null and form.parent['is_canceled'].vars.value == false %}
                <label class=" control-label" for="{{form.vars.id}}">{{'label.emails'|trans({}, 'InodataImperaBundle')}}* </label>
                <div class="controls sonata-ba-field sonata-ba-field-standard-natural  ">
                    <select multiple="multiple" class="ino_order_emails span5" data-url="#" data-value=" " url="{{path('inodata_impera_order_ajax_save_emails', {orderId: form.parent['id'].vars.value})}}">
                    </select>
                    <input type="hidden" value="{% if  form.vars.value is not empty%}{{form.vars.value}} {% else %}{{form.parent['customer'].vars.data.emails}},{% endif %}" id="{{form.vars.id}}" name="{{form.vars.full_name}}" class="span5 ino_order_emails">
                    <a href="javascript:void()" data-url="#" data-value=""
                       class="btn add-email-editable"> {{'label.add_email'|trans({}, 'InodataImperaBundle')}}</a>
                </div>
            {% endif %}
        </div>
    {% endif %}

    {% if form.vars.name == 'is_canceled'%}
        {{block('hidden_widget')}}
    {% endif %}

{% endblock %}

{% block ajax_entity_widget %}
    {% spaceless %}
        <input type="text" class="ajax-entity single {% if form.vars.attr['class'] is defined %}{{form.vars.attr['class']}}{%endif%}"
            {% for index, attr in form.vars.attr %} {%if index != "class" %}{{index}} = "{{attr}}"{%endif%}{%endfor%}
            id ="{{form.vars.id}}" name="{{form.vars.full_name}}" value="{{form.vars.value}}" text="{{form.vars.data}}"></input>
    {% endspaceless %}
{% endblock %}

src/Inodata/FloraBundle/Resources/views/Form/order_produc_impera.html.twig
<tr class="product-to-save" num-row="{% if num_row is defined%}{{num_row}}{%else%}{{loop.index-1}}{%endif%}">
    {% if uniqid is not defined%} {%set uniqid = form.parent.vars.id%}{%endif%}
    {% for field_name, field in product %}
        {% if (field_name != "_delete" and field_name != "id") %}
            {% set value = field %}
            {% if app.request.isXmlHttpRequest == false%} {% set value = field.vars.value%} {%endif%}
            <td>
                <a href="#" data-name="{{field_name}}"
                   class="{% if field_name == 'quantity' or field_name=='productCode' or  field_name == 'product' or field_name == 'discount'%}
                        edit-in-place{%endif%}" data-value="{{value}}" data-type="text" data-url="{{path("inodata_impera_orderproduct_ajax_editinplace", {"uniqid": uniqid})}}"
                        data-title="{{"label.write_new_value"|trans([], 'InodataImperaBundle')}}">
                {%if field_name == "productPrice" or field_name == "subtotal"%}
                    $ {{value|number_format(2, '.', ',')}}
                {% elseif field_name == "discount"%}
                    $
                    {% if app.request.isXmlHttpRequest == true%}
                        {{(product['productPrice']*(value/100))|number_format(2, '.', ',')}}
                    {% else %}
                        {{(product['productPrice'].vars.value*(value/100))|number_format(2, '.', ',')}}
                    {% endif%}
                    ({{value}}%)
                {%else%}
                    {{value}}
                {% endif %}
                </a>
                {%if  app.request.isXmlHttpRequest == true%}
                    <input type="hidden" id="{{uniqid}}_products_{{num_row}}_{{field_name}}" name="{{uniqid}}[products][{{num_row}}][{{field_name}}]"
                           value = "{{field}}" class="ino_order_product_{{field_name}} span5">
                {% else %}
                    <input type="hidden" id="{{field.vars.id}}" name="{{field.vars.full_name}}" value = "{{field.vars.value}}" class="{{field.vars.attr.class}}">
                {% endif%}
            </td>
        {% endif %}
    {% endfor%}
    <td>
        <a href="#" class="btn ino_order_product_remove" title="{{"label.remove"|trans({}, "InodataImperaBundle")}}">
            <i class="icon-remove"></i></a>
    </td>
</tr>